### ISSUE TITLE
No changelog/history for 1.3.1

### ISSUE THREAD

**Issue by sebix** [metachris/logzero#42]
What has been changed? it's neither in the tag, nor in current master.

**Comment by metachris** [comment]
Oh right, sorry. This patch is just a documentation fix - see #42

On Sep 14, 2017 15:29, "Sebastian" <notifications@github.com> wrote:

What has been changed? it's neither in the tag, nor in current master.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/metachris/logzero/issues/42>, or mute the thread

**Comment by sebix** [comment]
I guess you mean #41

**Comment by metachris** [comment]
Yes, thanks. Updated.
